/* automatically generated by rust-bindgen */

use odeconfig::*;

pub type dMessageFunction =
    extern "C" fn(errnum: ::libc::c_int, msg: *const ::libc::c_char,
                  ap: va_list) -> ();
extern "C" {
    pub fn dSetErrorHandler(_fn:
                                *mut ::std::option::Option<extern "C" fn()
                                                               -> ()>) -> ();
    pub fn dSetDebugHandler(_fn:
                                *mut ::std::option::Option<extern "C" fn()
                                                               -> ()>) -> ();
    pub fn dSetMessageHandler(_fn:
                                  *mut ::std::option::Option<extern "C" fn()
                                                                 -> ()>)
     -> ();
    pub fn dGetErrorHandler()
     -> *mut ::std::option::Option<extern "C" fn() -> ()>;
    pub fn dGetDebugHandler()
     -> *mut ::std::option::Option<extern "C" fn() -> ()>;
    pub fn dGetMessageHandler()
     -> *mut ::std::option::Option<extern "C" fn() -> ()>;
    pub fn dError(num: ::libc::c_int, msg: *const ::libc::c_char, ...) -> ();
    pub fn dDebug(num: ::libc::c_int, msg: *const ::libc::c_char, ...) -> ();
    pub fn dMessage(num: ::libc::c_int, msg: *const ::libc::c_char, ...)
     -> ();
}
