/* automatically generated by rust-bindgen */

use common::*;

#[link(name="ode")]
extern "C" {
    pub fn dTestRand() -> ::libc::c_int;
    pub fn dRand() -> ::libc::c_ulong;
    pub fn dRandGetSeed() -> ::libc::c_ulong;
    pub fn dRandSetSeed(s: ::libc::c_ulong) -> ();
    pub fn dRandInt(n: ::libc::c_int) -> ::libc::c_int;
    pub fn dRandReal() -> dReal;
    pub fn dPrintMatrix(A: *const dReal, n: ::libc::c_int, m: ::libc::c_int,
                        fmt: *const ::libc::c_char, f: *mut FILE) -> ();
    pub fn dMakeRandomVector(A: *mut dReal, n: ::libc::c_int, range: dReal)
     -> ();
    pub fn dMakeRandomMatrix(A: *mut dReal, n: ::libc::c_int,
                             m: ::libc::c_int, range: dReal) -> ();
    pub fn dClearUpperTriangle(A: *mut dReal, n: ::libc::c_int) -> ();
    pub fn dMaxDifference(A: *const dReal, B: *const dReal, n: ::libc::c_int,
                          m: ::libc::c_int) -> dReal;
    pub fn dMaxDifferenceLowerTriangle(A: *const dReal, B: *const dReal,
                                       n: ::libc::c_int) -> dReal;
}
