/* automatically generated by rust-bindgen */

use common::*;

#[link(name="ode")]
extern "C" {
    pub fn dSafeNormalize3(a: dVector3) -> ::libc::c_int;
    pub fn dSafeNormalize4(a: dVector4) -> ::libc::c_int;
    pub fn dNormalize3(a: dVector3) -> ();
    pub fn dNormalize4(a: dVector4) -> ();
    pub fn dPlaneSpace(n: dVector3, p: dVector3, q: dVector3) -> ();
    pub fn dOrthogonalizeR(m: dMatrix3) -> ();
}
